server:
  port:8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password : JAR@stc321#3
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

